import Link from 'next/link';
import { ExternalLink, Heart, AlertTriangle, BookOpen, Users } from 'lucide-react';

export const metadata = {
  title: 'About — California Proposition Predictor',
  description: 'About the CA Prop Predictor project: methodology, team, limits, and how to get involved.',
};

export default function AboutPage() {
  return (
    <div className="animate-fade-in" style={{ background: 'rgb(250 250 248)' }}>

      <section className="bg-white border-b-2 border-slate-700 py-10">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl">
            <p className="kicker mb-3">The Project</p>
            <h1 className="text-4xl md:text-5xl font-black text-slate-900 leading-tight mb-3"
              style={{ fontFamily: "'Playfair Display', Georgia, serif" }}>
              About the Project
            </h1>
            <p className="text-slate-600 font-serif leading-relaxed max-w-2xl">
              The California Proposition Predictor is a data-driven tool for understanding statewide ballot
              measures — built to help voters make more informed decisions before Election Day.
            </p>
          </div>
        </div>
      </section>

      <section className="py-12">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-0 border border-slate-200 bg-white">

            {/* Get Involved */}
            <div className="p-8 border-b md:border-b border-r-0 md:border-r border-slate-200">
              <div className="flex items-center gap-3 mb-5">
                <Heart className="h-5 w-5 text-indigo-600 shrink-0" />
                <h2 className="text-xl font-black text-slate-900"
                  style={{ fontFamily: "'Playfair Display', Georgia, serif" }}>
                  Get Involved
                </h2>
              </div>
              <p className="text-slate-600 font-serif text-sm leading-relaxed mb-5">
                This project is nonpartisan and independent. You can get involved by verifying our data sources,
                sharing the tool before elections, or using our open data for your own research.
              </p>
              <ul className="space-y-4">
                {[
                  { name: 'CA Secretary of State', url: 'https://www.sos.ca.gov/elections/ballot-measures', desc: 'Register to vote & official ballot info' },
                  { name: 'League of Women Voters', url: 'https://lwvc.org/', desc: 'Nonpartisan voter education resources' },
                  { name: 'CalMatters', url: 'https://calmatters.org/politics/elections/', desc: 'Independent California journalism' },
                  { name: 'Ballotpedia', url: 'https://ballotpedia.org/California_ballot_propositions', desc: 'Historical ballot data & analysis' },
                ].map(({ name, url, desc }) => (
                  <li key={name}>
                    <a href={url} target="_blank" rel="noopener noreferrer"
                      className="flex items-center justify-between group transition-colors">
                      <div>
                        <span className="text-sm font-semibold font-serif text-slate-800 group-hover:text-indigo-600 transition-colors">
                          {name}
                        </span>
                        <p className="text-xs text-slate-400 font-serif mt-0.5">{desc}</p>
                      </div>
                      <ExternalLink className="h-3.5 w-3.5 text-slate-300 group-hover:text-indigo-400 shrink-0 ml-3 transition-colors" />
                    </a>
                  </li>
                ))}
              </ul>
            </div>

            {/* Limits / Disclaimer */}
            <div className="p-8 border-b border-slate-200">
              <div className="flex items-center gap-3 mb-5">
                <AlertTriangle className="h-5 w-5 text-amber-600 shrink-0" />
                <h2 className="text-xl font-black text-slate-900"
                  style={{ fontFamily: "'Playfair Display', Georgia, serif" }}>
                  Limits & Disclaimer
                </h2>
              </div>
              <div className="space-y-3 text-sm text-slate-600 font-serif leading-relaxed">
                <p>
                  Predictions are generated by a statistical model trained on historical California ballot
                  proposition data. They are <strong>not</strong> guaranteed outcomes and should not be
                  treated as such.
                </p>
                <p>
                  Factors that cannot be fully modeled include: late-breaking news events, candidate endorsements,
                  grassroots mobilization, and shifts in voter sentiment close to Election Day.
                </p>
                <p>
                  Campaign finance data may lag real-time spending by several weeks due to Cal-Access
                  reporting schedules.
                </p>
                <div className="bg-amber-50 border border-amber-200 p-3 text-amber-800 italic mt-4">
                  This tool is for informational purposes only. Always consult the official CA Secretary
                  of State resources before casting your vote.
                </div>
              </div>
            </div>

            {/* Methodology */}
            <div className="p-8 border-r-0 md:border-r border-slate-200">
              <div className="flex items-center gap-3 mb-5">
                <BookOpen className="h-5 w-5 text-slate-700 shrink-0" />
                <h2 className="text-xl font-black text-slate-900"
                  style={{ fontFamily: "'Playfair Display', Georgia, serif" }}>
                  Methodology
                </h2>
              </div>
              <div className="space-y-3 text-sm text-slate-600 font-serif leading-relaxed">
                <p>Our prediction model weighs several key factors:</p>
                <ul className="space-y-2.5 mt-2">
                  {[
                    { label: 'Historical pass rates', desc: 'By category and ballot wording type' },
                    { label: 'Campaign finance ratio', desc: 'Support vs. opposition spending from Cal-Access' },
                    { label: 'Polling data', desc: 'When available and close to the election' },
                    { label: 'Semantic similarity', desc: 'ML-based matching to past propositions via embeddings' },
                    { label: 'Demographic modeling', desc: 'Census ACS data mapped to county-level patterns' },
                  ].map(({ label, desc }) => (
                    <li key={label} className="flex items-start gap-2">
                      <div className="w-1.5 h-1.5 bg-indigo-600 rounded-full mt-1.5 shrink-0" />
                      <div>
                        <span className="font-semibold text-slate-800">{label}</span>
                        <span className="text-slate-400"> — {desc}</span>
                      </div>
                    </li>
                  ))}
                </ul>
                <p className="pt-1">
                  The model is a logistic regression ensemble calibrated on 1980–2024 California
                  ballot proposition outcomes across {'>'}1,200 measures.
                </p>
                <Link href="/propositions"
                  className="inline-flex items-center gap-1 text-xs text-indigo-600 hover:text-indigo-700 font-serif uppercase tracking-wider mt-1 transition-colors">
                  Browse proposition data →
                </Link>
              </div>
            </div>

            {/* Meet the Team */}
            <div className="p-8">
              <div className="flex items-center gap-3 mb-5">
                <Users className="h-5 w-5 text-emerald-700 shrink-0" />
                <h2 className="text-xl font-black text-slate-900"
                  style={{ fontFamily: "'Playfair Display', Georgia, serif" }}>
                  Meet the Team
                </h2>
              </div>
              <p className="text-sm text-slate-600 font-serif leading-relaxed mb-5">
                Built by a group of data scientists and civic technologists interested in making
                California ballot information more accessible and transparent to voters.
              </p>
              <div className="space-y-3">
                {[
                  { name: 'Data Science', role: 'Prediction model & statistical analysis' },
                  { name: 'Engineering', role: 'API integrations & frontend development' },
                  { name: 'Policy Research', role: 'Historical proposition analysis & categorization' },
                ].map(({ name, role }) => (
                  <div key={name} className="flex items-center gap-3 p-3 bg-slate-50 border border-slate-200">
                    <div className="w-8 h-8 bg-indigo-100 border border-indigo-200 flex items-center justify-center shrink-0">
                      <Users className="h-4 w-4 text-indigo-600" />
                    </div>
                    <div>
                      <p className="text-sm font-semibold font-serif text-slate-900">{name}</p>
                      <p className="text-xs text-slate-400 font-serif">{role}</p>
                    </div>
                  </div>
                ))}
              </div>
              <p className="text-xs text-slate-400 font-serif mt-5 italic">
                This is a civic technology project. Not affiliated with any political party or campaign.
              </p>
            </div>

          </div>
        </div>
      </section>

    </div>
  );
}
